### ISSUE TITLE
Include Flyway and CF version in the release note

### ISSUE THREAD

**Issue by louisthomas** [emerald-squad/cf-flyway-resource#4]
When I do a database migration, I need a specific version of Flyway. It will help me if you add it in the release note.

Or you can match the release version with Flyway release.

By the way, nice Concourse resource, good job!

**Comment by jpmorin** [comment]
We have added env vars in the Dockerfile to manage cli version when building new images.

```bash
ENV FLYWAY_VERSION=6.0.4
ENV CF_CLI_VERSION=6.46.1
```

You can also consult the [release](https://github.com/emerald-squad/cf-flyway-resource/releases) page for version information.
